### ISSUE TITLE
Cannot find module @agentic/stdlib/ai-sdk & @agentic/stdlib/e2b

### ISSUE THREAD

**Issue by olivermontes** [transitive-bullshit/agentic#649]
Cannot find module '@agentic/stdlib/ai-sdk' or its corresponding type declarations.
  There are types at '/example/node_modules/@agentic/stdlib/dist/sdks/ai-sdk.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.ts(2307)

Cannot find module '@agentic/stdlib/e2b' or its corresponding type declarations.
  There are types at '/example/node_modules/@agentic/stdlib/dist/tools/e2b.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.ts(2307)

Stack:
pnpm install @agentic/stdlib
node --version = v20.11.0
"next": "14.2.1"
"@agentic/stdlib": "^6.2.4",

**Comment by transitive-bullshit** [comment]
This should no longer be an issue given that all tools are now isolated to their individual packages.

See the updated docs for more info: https://agentic.so
