### ISSUE TITLE
Do you want help with docs? 

### ISSUE THREAD

**Issue by jdbohrman** [transitive-bullshit/agentic#651]
I can knock out a pretty sick page in about a week using [Starlight](https://starlight.astro.build/). Love this library dawg. You should grab a domain if that's a route you wanna take.

**Comment by transitive-bullshit** [comment]
Thanks, James.

Definitely looking to add docs, though I'd prefer to use https://mintlify.com which I had a stalled first pass at here: https://github.com/transitive-bullshit/agentic/tree/feature/docs

**Comment by transitive-bullshit** [comment]
Initial docs are now up at https://agentic.so – would love any feedback :)
