### ISSUE TITLE
You should look into Speakeasy for an SDK and OpenAPI

### ISSUE THREAD

**Issue by jdbohrman** [transitive-bullshit/agentic#652]
Having something like this may help streamline the data connectors

https://www.speakeasy.com/

**Comment by transitive-bullshit** [comment]
Looks interesting && def a lot of inspiration to be taken from them, especially around their LLM-augmented API understanding and SDK codegen.

Also in a similar boat is [stainless](https://www.stainlessapi.com/) and [fern](https://github.com/fern-api/fern).

Closing for now as I think it's unlikely we'll be making use of any of these anytime soon.
