### ISSUE TITLE
Wikibase module-not-found error in v.6.6.0

### ISSUE THREAD

**Issue by QuinnStraus** [transitive-bullshit/agentic#653]
I just installed agentic for the first time in my Next.js (app router) project and was greeted by the following error when trying to start the server.

⨯ ./node_modules/@agentic/stdlib/dist/index.js:6138:1
Module not found: Can't resolve 'wikibase-sdk/wikidata.org'

I was only importing WolframAlphaClient and createAISDKTools, so I don't think I should have needed to install wikibase-sdk. 
Downgrading to 6.5.0 seemed to fix the problem.

**Comment by transitive-bullshit** [comment]
Thanks for the report, Quinn; this was definitely a mistake on my part.

I've just pushed https://github.com/transitive-bullshit/agentic/releases/tag/v6.6.1 which should fix things for you.

The long-term fix to ensure this doesn't repro is comprised of https://github.com/transitive-bullshit/agentic/issues/654 and https://github.com/transitive-bullshit/agentic/issues/655, both of which I hope to get to this week.
