### ISSUE TITLE
@agentic/core breaks edge runtime

### ISSUE THREAD

**Issue by oalexdoda** [transitive-bullshit/agentic#677]
Hi,

There's a dependency in @agentic/core called `hash-object` which requires `node:crypto` behind the scenes.

This causes runtime edge to break in Next.js

Can that dependency be replaced with something else?

Thanks!

<img width="1095" alt="image" src="https://github.com/user-attachments/assets/4ef31876-40b3-4fe8-9e92-4286dba181bf">

**Comment by transitive-bullshit** [comment]
Good catch @oalexdoda 

Yes, it should be easy to swap `hash-object` out. Will work on this shortly. Thanks!

**Comment by oalexdoda** [comment]
Thank you @transitive-bullshit ! (btw weird name to tag lol)

Looking forward to the release!

**Comment by transitive-bullshit** [comment]
Should be fixed in https://github.com/transitive-bullshit/agentic/releases/tag/7.2.0

**Comment by oalexdoda** [comment]
Awesome, thank you @transitive-bullshit - really appreciate you!
